### ISSUE TITLE
Roadmaps are not loading (error msg: `error parsing issue`)

### ISSUE THREAD

**Issue by AlexxNica** [pln-planning-tools/Starmap#324]
Roadmaps are not loading. It seems to be an error with the parser. Probably a regression from #315?

Tested on https://starmap.site/roadmap/github.com/filecoin-station/roadmap/issues/1

### Response from the API:

https://starmap.site/api/roadmap?owner=filecoin-station&repo=roadmap&issue_number=1
```json
{"errors":[{"issueUrl":"https://starmap.site/roadmap/github.com/filecoin-station/roadmap/issues/1","issueTitle":"https://starmap.site/roadmap/github.com/filecoin-station/roadmap/issues/1","errors":[{"userGuideUrl":"https://github.com/pln-planning-tools/Starmap/blob/main/User%20Guide.md#children","title":"Error parsing issue","message":"Unsupported URL: https://starmap.site/roadmap/github.com/filecoin-station/roadmap/issues/1"}]},{"issueUrl":"https://github.com/filecoin-station/roadmap/issues/1","issueTitle":"Filecoin Station 2023 Roadmap","errors":[{"userGuideUrl":"https://github.com/pln-planning-tools/Starmap/blob/main/User%20Guide.md#children","title":"Error resolving children","message":"No children found, is this a root issue?"}]}],"data":{"labels":["roadmap"],"completion_rate":0,"due_date":"2023-12-31","html_url":"https://github.com/filecoin-station/roadmap/issues/1","group":"root","title":"Filecoin Station 2023 Roadmap","state":"open","node_id":"I_kwDOIUF5GM5U5JPE","parent":{"completion_rate":0,"due_date":""},"children":[]},"pendingChildren":[]}
```

### Screenshot
<img width="753" alt="image" src="https://user-images.githubusercontent.com/14338588/219539920-d1b464f6-e779-4214-af41-f99e395acd9e.png">

**Comment by AlexxNica** [comment]
I think we need to revert that PR until we figure out what's causing the error.

cc @SgtPooki

**Comment by AlexxNica** [comment]
Deployment from the previous commit is working fine: https://starmaps-ccad3vayi-ipfs-ignite.vercel.app/roadmap/github.com/filecoin-station/roadmap/issues/1

Deployment from the PR is not working: https://starmaps-o358kbppd-ipfs-ignite.vercel.app/roadmap/github.com/filecoin-station/roadmap/issues/1

I'll go ahead and revert that PR while we fix whatever is causing the issue.

**Comment by SgtPooki** [comment]
Opened WIP PR https://github.com/pln-planning-tools/Starmap/pull/333 to address this

**Comment by SgtPooki** [comment]
error reproduced locally:

```
error: Error: Error resolving children: Error: Unsupported URL: https://starmap.site/roadmap/github.com/filecoin-station/roadmap/issues/1
    at resolveChildren (webpack-internal:///(api)/./lib/backend/resolveChildren.ts:30:11)
    at async resolveChildrenWithDepth (webpack-internal:///(api)/./lib/backend/resolveChildrenWithDepth.ts:14:20)
    at async handler (webpack-internal:///(api)/./pages/api/roadmap.ts:60:20)
    at async Object.apiResolver (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async DevServer.runApi (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/router.js:252:36)
    at async DevServer.run (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/base-server.js:365:29)
    at async DevServer.run (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/dev/next-dev-server.js:709:20)
    at async DevServer.handleRequest (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/base-server.js:303:20)
Error: No children found, is this a root issue?
    at handler (webpack-internal:///(api)/./pages/api/roadmap.ts:63:17)
    at async Object.apiResolver (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async DevServer.runApi (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/router.js:252:36)
    at async DevServer.run (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/base-server.js:365:29)
    at async DevServer.run (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/dev/next-dev-server.js:709:20)
    at async DevServer.handleRequest (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/base-server.js:303:20)
```
