### ISSUE TITLE
bug: Uncaught (in promise) Error: Unsupported URL: https://github.com/issues/

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/Starmap#372]
[reported in slack](https://filecoinproject.slack.com/archives/C0418TBQ9CH/p1684146518603149) 

problem url: https://starmap.site/roadmap/github.com/filecoin-station/roadmap/issues/1

```
paramsFromUrl.ts:17 Uncaught (in promise) Error: Unsupported URL: https://github.com/issues/
    at s (paramsFromUrl.ts:17:11)
    at [...slug].tsx:147:45
    at s (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at forEach.e.<computed> [as next] (runtime.js:97:21)
    at n (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12

```

![image](https://github.com/pln-planning-tools/Starmap/assets/1173416/2a912c8d-2d32-4e5f-9f9a-3d000ee9b2fb)

**source:** 
* https://github.com/pln-planning-tools/Starmap/blob/be391028ce5d1cedb0ebe6015417f6a83d849b45/lib/paramsFromUrl.ts#L17
* https://github.com/pln-planning-tools/Starmap/blob/be391028ce5d1cedb0ebe6015417f6a83d849b45/pages/roadmap/%5B...slug%5D.tsx#L147

**Comment by SgtPooki** [comment]
I attempted to load this URL, got a successfully rendered roadmap, and then refreshed and it succeeded again. 

I removed my “debug” item in localStorage and reloaded, and got the same error as reported; investigating now.

**Comment by SgtPooki** [comment]
it seems like the children of https://github.com/filecoin-station/roadmap/issues/12 are not being recognized properly.

**Comment by SgtPooki** [comment]
The children parsing logic was failing on parsing a `linePiece` that was equal to `###` due to:

https://github.com/pln-planning-tools/Starmap/blob/be391028ce5d1cedb0ebe6015417f6a83d849b45/lib/getValidUrlFromInput.ts#L1-L22

returning `https://github.com/issues/##` when called by

https://github.com/pln-planning-tools/Starmap/blob/be391028ce5d1cedb0ebe6015417f6a83d849b45/lib/parser.ts#L94
